import {fileURLToPath} from 'node:url';
process.chdir(fileURLToPath(new URL('../../',import.meta.url)));
import {strict as assert} from 'node:assert';
import {readFileSync,mkdirSync} from 'node:fs';
import {build} from 'esbuild';
import {decode,estimate,half,norm,dot} from '../web/search-data.js';
mkdirSync('work/hosted-tests',{recursive:true});
await build({absWorkingDir:process.cwd(),entryPoints:['backend/src/chat.ts'],outfile:'work/hosted-tests/chat.mjs',bundle:true,platform:'node',format:'esm'});
const {chat,validateChat}=await import('../../work/hosted-tests/chat.mjs');
assert.equal(validateChat({messages:[{role:'system',content:'bad'}]}),null);
assert.equal(validateChat({messages:[{role:'user',content:42}]}),null);
assert.equal(validateChat({messages:[{role:'user',content:'x'.repeat(6001)}]}),null);
assert.equal(validateChat({messages:[{role:'user',content:'Role'}],draft:{notes:'private'}}),null);
let called=0,requestBody;
globalThis.fetch=async(url,options)=>{called++;requestBody=JSON.parse(options.body);return Response.json({id:'test',status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({message:'Here is your draft',title:'Engineer',location:'Remote, US',jd:'Build software.',ready:true})}]}],usage:{input_tokens:1,output_tokens:1}})};
const env={OPENAI_KEY:'test-key',RATELIMIT:{getByName:()=>({hit:async()=>({ok:true,resetMs:0})})}};
const req=(body,origin='https://example.com')=>new Request('https://example.com/chat',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
const body={messages:[{role:'user',content:'I want to build software remotely in the US.'}],draft:''};
assert.equal((await chat(req(body,'https://other.example'),env)).status,403);
assert.equal((await chat(req({}),env)).status,400);
assert.equal(called,0);
const success=await chat(req(body),env);assert.equal(success.status,200);assert.equal((await success.json()).ready,true);assert.equal(requestBody.store,false);assert.equal(requestBody.text.format.strict,true);assert.equal(requestBody.max_output_tokens,3600);
const limited={...env,RATELIMIT:{getByName:()=>({hit:async()=>({ok:false,resetMs:4000})})}};
assert.equal((await chat(req(body),limited)).status,429);assert.equal(called,1);
globalThis.fetch=async()=>{throw Error('secret-token-detail')};const fail=await chat(req(body),env);assert.equal(fail.status,503);assert.ok(!(await fail.text()).includes('secret-token'));
assert.equal(half(0x3c00),1);assert.equal(half(0xbc00),-1);assert.equal(half(0),0);
assert.ok(Math.abs(dot(norm([3,4]),norm([3,4]))-1)<1e-6);
const models={salary:{w:[0,0,0],b:Math.log(150000),sigma:.2},age:{kind:'ridge',w:[0,0,0],b:Math.log(31)}};
const raw={v:Buffer.from(new Float32Array([1,0,0]).buffer).toString('base64')};
const j=estimate({v:raw.v,t:'Engineer',rm:'unknown',ci:[],rg:[],u:'javascript:alert(1)'},models);assert.ok(Math.abs(j.agp-30)<1e-8);assert.ok(j.est.hi>=j.est.lo);assert.equal(j.u,'');assert.equal(decode(raw.v).length,3);
const html=readFileSync('backend/web/search.html','utf8');assert.ok(!/__[A-Z_]+__/.test(html));assert.ok(!html.includes("fetch('/event'"));assert.ok(html.includes("hosted.id"));assert.ok(html.includes('getSearch'));
for(const id of ['sortbtn','enrichbtn','export','f-el','f-fr','f-sa','f-rm','f-sn','f-co','f-ci','f-rg','f-rf','f-et','f-in','f-cs','f-g','f-c','f-a','f-ag','helpbtn','toggleIdeal'])assert.ok(html.includes(`id="${id}"`),id);
const script=html.match(/<script type="module">([\s\S]*?)<\/script>/)[1];
await build({stdin:{contents:script,loader:'js',resolveDir:process.cwd()},bundle:false,write:false,format:'esm'});
console.log('PASS: chat validation, AI request, rate limit, safe failures, model math, URL safety, shared search compilation and every facet.');
